// Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the MIT Licence.
// See the LICENCE file in the repository root for full licence text.

namespace osu.Game.Rulesets.Objects.Types
{
    /// <summary>
    /// Marks a nested <see cref="osu.Game.Rulesets.Objects.HitObject"/> as a tick-type sub-component
    /// of a slider (i.e. generated by <see cref="osu.Game.Rulesets.Objects.SliderEventType.Tick"/>).
    /// </summary>
    /// <remarks>
    /// This interface exists so that core-game code (e.g. pool-sizing metadata) can count slider ticks
    /// without taking a compile-time dependency on any ruleset assembly.
    /// </remarks>
    public interface ISliderTick
    {
    }
}
